#!/bin/bash

## local variables
CORRECT_USER='n'

## disable su for all users
printf "\n# Disable use of 'sudo su'" >> /etc/pamd.d/su
printf '\nauth required pam_wheel.so use_uid' >> /etc/pam.d/su

## run logic with valid input
while [ "${CORRECT_USER,,}" != 'y' ] && \
    [ "${CORRECT_USER,,}" != 'yes' ] && \
    [ "${CORRECT_USER,,}" != 'true' ] && \
    [ "${CORRECT_USER,,}" != 'ok' ]; do

    ## prompt input
    echo 'We need to rename the default \'pi\' username.'
    read -p 'Enter new username > ' NEW_USER
    read -p 'Is this correct (y) > ' CORRECT_USER

    ## enforce limited group
    user -G sudo "$NEW_USER"

    ## rename 'pi' username to supplied input
    systemctl stop autologin@tty1
    systemctl daemon-reload
    usermod -l "$NEW_USER" -d /home/"$NEW_USER" -m pi
    ls -al /home
    mkdir /home/"$NEW_USER"
    chown "$NEW_USER":"$NEW_USER" /home/"$NEW_USER"
    ls -al /home
    systemctl start autologin@tty1

    ## reboot
    reboot
done
