#!/bin/bash

## replace default ssh keys
sudo rm -rf /etc/ssh/ssh_host_* && sudo dpkg-reconfigure openssh-server

## configure ssh
if [ -f '/etc/ssh/sshd_config' ]; then
    ## disallow root ssh
    sudo sed -i 's/PermitRootLogin yes/PermitRootLogin no/g' /etc/ssh/sshd_config
    sudo sed -i 's/PermitRootLogin without-password/PermitRootLogin no/g' /etc/ssh/sshd_config

    ## disallow more than 5 failed ssh login
    sudo chmod 777 /etc/ssh/sshd_config
    sudo printf '\nMaxAuthTries 5' >> /etc/ssh/sshd_config
    sudo chmod 644 /etc/ssh/sshd_config
fi

## ensure us keyboard layout
sudo sed -i 's/XKBLAYOUT=".*"/XKBLAYOUT="us"/g' /etc/default/keyboard

## disable bluetooth
sudo printf '\ndtoverlay=pi3-disable-bt' >> /boot/config.txt

## gui configurations
if [ -f '/etc/lightdm/lightdm.conf' ]; then
    ## require login password with gui
    sudo sed -i 's/autologin-user=pi/#autologin-user=pi/g' /etc/lightdm/lightdm.conf

    ## enforce screensaver with password
    sudo apt-get -y install xscreensaver
    sudo sed -i 's/\*lock::[[:space:]]*False/\*lock:                  True/g' /etc/X11/app-defaults/XScreenSaver
fi

## change default 'raspberry' password
passwd

## set root password
sudo passwd root

## reboot: some configurations require reboot
sudo reboot
